version: "3.5"
services:
    service-chat:
        image: 0917798273/docker-demo:backend_graphQL
        volumes: 
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 4000:4000
        environment:
            - NODE_ENV=${NODE_ENV}

            